version: '3.8'

services:
  trivia-app:
    image: ghcr.io/yourusername/tobi-trivia:latest
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: tobi-trivia-app
    platform: linux/amd64  # Will auto-detect and use appropriate architecture

  # Alternative: Build locally if needed
  trivia-app-local:
    build: .
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: tobi-trivia-app-local
    profiles:
      - local-build

  # Development service
  trivia-app-dev:
    build:
      context: .
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    profiles:
      - dev